# Generated by Django 5.2.7 on 2026-03-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_description_project_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('health_status', models.CharField(choices=[('ON TRACK', 'On Track'), ('DELAYED', 'Delayed'), ('INACTIVE', 'Inactive')], default='ON TRACK', max_length=20)),
                ('logo_color', models.CharField(default='#111827', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='health',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Red', 'Red')], default='Green', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, help_text='0 to 100'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text='e.g., PRJ-9402', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Consultation', help_text='e.g., Development, Design, Launch', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client'),
        ),
    ]
